tags:
- name: Leave Application
  description: Leave application API

paths:
# [GET] Application
  /api/leave-application:
    get:
      tags:
      - Application
      summary: Find All Application
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'

# [POST] application
    post:
      tags:
      - Application
      summary: Add leave Application
      parameters:
      - name: body
        in: body
        description: leave Application Data
        required: true
        schema:
          $ref: '#/definitions/Application'
      responses:
        201:
          description: 'Created'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [GET] Application/id
  /api/leave-application/{id}:
    get:
      tags:
      - Application
      summary: Find leave Application By Id
      parameters:
      - name: id
        in: path
        description: leave Application Id
        required: true
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [PUT] application/id
    put:
      tags:
      - Application
      summary: Update leave Application By Id
      parameters:
      - name: id
        in: path
        description: leave Application Id
        required: true
      - name: body
        in: body
        description: leave Application Data
        required: true
        schema:
          $ref: '#/definitions/Application'
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [DELETE] Application/id
    delete:
      tags:
      - Application
      summary: Delete leave Application By Id
      parameters:
      - name: id
        in: path
        description: leave Application Id
        required: true
        schema:
          type: string
      security:
        - jwt: []
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# definitions
definitions:
  Leave Application:
    type: object
    required:
        - from_date
        - start_time
        - to_date
        - leave_type_id
    properties:
      id:
        type: string
        description: Application Id
      employee_id:
        type: string
        description: employee id
      leave_type_id:
        type: string
        description: leave type
        enum: ["Annual","Casual","Sick","Without Pay","Maternity"]
      from_date:
        type: date
        description: start time
      to_date:
        type: date
        description: end time
      posting_date:
        type: date
        description: date posted
      leave_approver:
        type: date
        description: Who approves leave
      reason:
        type: string
        description: reason for leave
      status:
        type: string
        description: leave status

schemes:
 - https
 - http
